Repository swisstopo/swissgeol-assets-suite, pull requests merged in 2024-06, with the labels that each got.

#140 Feature 11:added first cypress test
  e2e/.cypress-cucumber-preprocessorrc.json
  e2e/.editorconfig
  e2e/.gitignore
  e2e/README.md
  e2e/cypress.config.ts
  e2e/cypress/e2e/common/login.ts
  e2e/cypress/e2e/search.feature
  e2e/cypress/e2e/search/search-steps.ts
  e2e/cypress/results/.gitkeep
  e2e/cypress/support/commands/login.commands.ts
  e2e/cypress/support/config/config.ts
  e2e/cypress/support/e2e.ts
  e2e/package-lock.json
  e2e/package.json
  e2e/tsconfig.json
Labels: code-quality

#153 Feature 150: Bug - File Download schlägt fehl
  apps/server-asset-sg/src/utils/file/common.ts
  libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
  libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
  libs/auth/src/lib/services/auth.interceptor.ts
Labels: bug

#152 Feature 149: Cypress logout test
  e2e/cypress/e2e/logout.feature
  e2e/cypress/e2e/logout/logout-steps.ts
  e2e/cypress/e2e/search.feature
Labels: code-quality

#157 Feature 148: Create elastic search index
  e2e/cypress/e2e/common/create-elastic-index.ts
  e2e/cypress/e2e/common/create-test-asset.ts
  e2e/cypress/e2e/create-elastic-index.feature
  e2e/cypress/e2e/search.feature
  e2e/cypress/e2e/search/search-steps.ts
  e2e/cypress/support/commands/helper.commands.ts
  e2e/cypress/support/commands/login.commands.ts
  e2e/cypress/support/e2e.ts
Labels: code-quality

#175 Fix: Elastic queries only escape the first occurence of matching characters
  apps/server-asset-sg/src/features/assets/search/asset-search.service.ts
Labels: bug

#176 Feature 167: Add spinner to file download
  libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.html
  libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.scss
  libs/asset-viewer/src/lib/components/asset-search-detail/asset-search-detail.component.ts
Labels: enhancement

#178 Feature 138: Filter "Keine Sprache" bei Suchfiltern
  apps/client-asset-sg/src/app/i18n/de.ts
  apps/client-asset-sg/src/app/i18n/en.ts
  apps/client-asset-sg/src/app/i18n/fr.ts
  apps/client-asset-sg/src/app/i18n/it.ts
  apps/client-asset-sg/src/app/i18n/rm.ts
  apps/server-asset-sg/jest.config.ts
  apps/server-asset-sg/src/features/assets/search/asset-search.service.spec.ts
  apps/server-asset-sg/src/features/assets/search/asset-search.service.ts
  libs/asset-viewer/src/lib/asset-viewer.module.ts
  libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.html
  libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.scss
  libs/asset-viewer/src/lib/components/asset-search-filter-list/asset-search-filter-list.component.ts
  libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.html
  libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.scss
  libs/asset-viewer/src/lib/components/asset-search-refine/asset-search-refine.component.ts
  libs/asset-viewer/src/lib/components/asset-viewer-page/asset-viewer-page.component.ts
  libs/asset-viewer/src/lib/state/asset-search/asset-search.actions.ts
  libs/asset-viewer/src/lib/state/asset-search/asset-search.effects.ts
  libs/asset-viewer/src/lib/state/asset-search/asset-search.reducer.ts
  libs/asset-viewer/src/lib/state/asset-search/asset-search.selector.ts
  libs/client-shared/src/lib/components/index.ts
  libs/client-shared/src/lib/components/smart-translate.pipe.ts
  libs/shared/src/lib/models/asset-search/asset-search-query.dto.ts
  libs/shared/src/lib/models/asset-search/asset-search-query.ts
Labels: enhancement
